CREATE (Rincon_del_Steak:Restaurante {nombre: 'Rincón del Steak', ubicacion: '5ta ave. 10-30 zona 9', precio: '117 GTQ - 311 GTQ', tipo_comida: ['Comida de mar', 'Comida internacional'], ambiente: ['Familiar', 'Romantico', 'Negocios'], tipo_servicio: ['Domicilio', 'A la mesa', 'Para llevar', 'Bar'], horario: ['Lunes - Sábado: 12:00 pm - 22:00 pm', 'Domingo: 11:00 am - 21:00 pm'],web:'https://rincondelsteak.com.gt/menus-2',img1:'https://rincondelsteak.com.gt/wp-content/uploads/2022/10/4.jpg',img2:'https://rincondelsteak.com.gt/wp-content/uploads/2022/10/17.jpg',img3:'https://rincondelsteak.com.gt/wp-content/uploads/2022/10/8.jpg'})
CREATE (En_Un_Dos_Por_Crepes:Restaurante {nombre: 'En Un Dos Por Crepes', ubicacion: 'Ciudad de Guatemala, 8A Calle 3-56, zona 10', precio: '14 GTQ - 29 GTQ', tipo_comida: 'Comida internacional', ambiente: ['Aire libre','Familiar'], tipo_servicio:['Para llevar','A la mesa','Domicilio'], horario: 'Lunes - Viernes: 10:30 am - 20:00 pm',web:'https://www.facebook.com/enundosporcrepes/?locale=es_LA',img1:'https://5dc93791f535c5b6680b-504f722ff1ef8102127dae26bdb15aa6.ssl.cf1.rackcdn.com/pix_16_665_1478_63c36edc2df1e.jpg',img2:'https://media-cdn.tripadvisor.com/media/photo-s/11/1d/68/29/photo1jpg.jpg',img3:'https://www.guatemala.com/fotos/2018/10/En-Un-Dos-Por-Crepes-885x500.jpg'})
CREATE (Cadejo_Brewing_Company_Beerhouse_and_Grill:Restaurante {nombre: 'Cadejo Brewing Company Beerhouse & Grill', ubicacion: '13 Calle 4, Cdad. de Guatemala', precio: '45 GTQ - 130 GTQ', tipo_comida: ['Vegano','Vegetariano','Bar','Comida de mar'], ambiente: ['Familiar','Aire libre','Entretenimiento'], tipo_servicio:['A la mesa','Domicilio','Para llevar'], horario: ['Lunes: 11:30 am - 23:59 pm','Martes - Viernes: 12:00 pm - 23:00 pm','Sábado: 12:00 pm - 1:00 am','Domingo: 12:00 pm - 22:00 pm'],web:'https://www.facebook.com/cervezacadejogt/',img1:'https://media-cdn.tripadvisor.com/media/photo-s/16/df/bf/8c/barra.jpg',img2:'https://media-cdn.tripadvisor.com/media/photo-s/18/77/b9/c2/alitas-30u.jpg',img3:'https://media-cdn.tripadvisor.com/media/photo-s/18/2c/d0/f1/img-20190703-183719-largejpg.jpg'})
CREATE (_100_montaditos:Restaurante {nombre: '100 montaditos', ubicacion: ['Bulevar El Naranjo, Cdad. de Guatemala','7 Ave. 6-40 Zona 11 C.C. Majadas Once'], precio: '15 GTQ - 75 GTQ', tipo_comida: ['Comida internacional','Vegetariano'], ambiente: 'Familiar', tipo_servicio:['A la mesa','Para llevar','Bar'], horario: 'Lunes - Domingo: 10:00 am - 23:00 pm',web:'https://spain.100montaditos.com/es/',img1:'https://empresaexterior.com/upload/images/10_2018/6278_100m_cr.jpg',img2:'https://imagenes.20minutos.es/files/image_980_553/uploads/imagenes/2022/09/14/100-montaditos.jpeg',img3:'https://www.guatemala.com/fotos/201708/100-montaditos1-885x500.jpg'})
CREATE (Baoz:Restaurante {nombre: 'Baoz', ubicacion: ['Plaza centro comercial Zona 4 ( carrion ) 3er nivel 6a Avenida Pista Izquierda, 0-79, Zona 4, Guatemala, Guatemala','Plaza Madero Atanasio zona 12 Diagonal 3 calzada atanasio tzul 17-13 zona 12 plaza madero atanasio local 14 '], precio: '20 GTQ - 47 GTQ', tipo_comida: 'Comida internacional', ambiente: 'Familiar', tipo_servicio:['A la mesa','Para llevar'], horario: ['Lunes: 12:30 pm - 18:00 pm','Martes - Domingo: 12:30 pm - 19:00 pm'],web:'https://www.facebook.com/baozgt/',img1:'https://media-cdn.tripadvisor.com/media/photo-s/17/41/a3/31/plato-grande-con-dos.jpg',img2:'https://media-cdn.tripadvisor.com/media/photo-f/16/f2/0d/c6/getlstd-property-photo.jpg',img3:'https://media-cdn.tripadvisor.com/media/photo-s/17/41/a5/22/baoz-plaza-el-recreo.jpg'})
CREATE (Restaurante_El_Cafetal:Restaurante {nombre: 'Restaurante El Cafetal', ubicacion: 'Avenida la Reforma y 14 Calle, Ciudad de Guatemala 01010 Guatemala', precio: '117 GTQ - 234 GTQ', tipo_comida: ['Comida internacional', 'Vegano', 'Vegetariano', 'Gourmet', 'Infantil'], ambiente: ['Familiar', 'Negocios', 'Romántico'], tipo_servicio: ['Para llevar', 'A la mesa', 'Bufet'], horario: 'Lunes - Domingo: 7:30 am - 23:00 pm', web: 'https://www.marriott.com/hotels/einterface/GUAWI',img1:'https://mrmenu.co/media/images/el_cafetal_2.original.jpg',img2:'https://fastly.4sqi.net/img/general/width960/80424677_ExmA4gzjwtoWYtYnAHS9XMK8LzamkSNzVEJUR7dRmjw.jpg',img3:'https://dea154aeb528bee620f5-799733fd03b9298a9f65fee6178f3d08.ssl.cf1.rackcdn.com/pix_16_555_19523_60e1fc9e1fb9f.jpg'})
CREATE (Carpaccio_Restaurante:Restaurante {nombre: 'Carpaccio Restaurante', ubicacion: '14 calle 0-25 zona 10 Frente al Westin Camino Real Guatemala, 01010', precio: '195 GTQ - 779 GTQ', tipo_comida: ['Comida internacional', 'Comida de mar', 'Bar', 'Gourmet', 'Vegetariano'], ambiente: ['Familiar', 'Romántico', 'Aire libre', 'Negocios'], tipo_servicio: 'A la mesa', horario: ['Lunes - Sabado: 11:00 am - 22:30 pm','Domingo: Cerrado'], web: 'https://carpacciorestaurante.com/',img1:'https://carpacciorestaurante.com/wp-content/uploads/2019/11/carpaccio-restaurante-2019-2.jpg',img2:'https://carpacciorestaurante.com/wp-content/uploads/2019/11/carpaccio-restaurante-29.jpg',img3:'https://carpacciorestaurante.com/wp-content/uploads/2019/11/carpaccio-restaurante-31.jpg'})
CREATE (Pronto_Pizza:Restaurante {nombre: 'Pronto Pizza', ubicacion: '16 avenida 9-11 zona 11, Colonia Carabanchel, Guatemala City, Guatemala', precio: '35 GTQ - 165 GTQ', tipo_comida: 'Comida rapida', ambiente: ['Familiar', 'Aire libre'], tipo_servicio: ['A la mesa', 'Domicilio', 'Para llevar'], horario: ['Lunes - Viernes: 12:00 pm - 21:00 pm','Sabado - Domingo: 13:00 pm - 21:00pm'], web: 'https://www.facebook.com/prontopizzagt/?locale=es_LA',img1:'https://media-cdn.tripadvisor.com/media/photo-s/1b/18/e0/2a/deliciosa-pizza-adobo.jpg',img2:'https://media-cdn.tripadvisor.com/media/photo-s/1b/18/e0/66/luch-time.jpg',img3:'https://media-cdn.tripadvisor.com/media/photo-f/1b/18/e0/0c/como-ninguna-nuestra.jpg'})
CREATE (Pizza_Vesuvio:Restaurante {nombre: 'Pizza Vesuvio', ubicacion: ['6 Avenida zona 4, Guatemala, Guatemala', 'Boulevard Vista Hermosa, Guatemala 01015, Gt, GT-GU 01015'], precio: '35 GTQ - 165 GTQ', tipo_comida: ['Comida internacional', 'Bar', 'Vegetariano'], ambiente: ['Familiar', 'Aire libre'], tipo_servicio: ['A la mesa', 'Domicilio', 'Para llevar'], horario: 'Lunes - Domingo: 10:00 am - 21:30 pm', web: 'https://www.vesuvio.com.gt/',img1:'https://media-cdn.tripadvisor.com/media/photo-s/0c/53/fc/cd/photo3jpg.jpg',img2:'https://media-cdn.tripadvisor.com/media/photo-s/12/a4/2d/55/pizzeria-vesuvio.jpg',img3:'https://d1ralsognjng37.cloudfront.net/14780e17-d0ed-4875-9131-eb24f882b884.jpeg'})
CREATE (Dennys:Restaurante {nombre: 'Dennys', ubicacion: 'Paseo Liberacion z.9 Vista Hermosa z.15', precio: '30 GTQ - 150 GTQ', tipo_comida: ['Vegetariano', 'Comida internacional', 'Infantil', 'Saludable'], ambiente: ['Familiar'], tipo_servicio: ['A la mesa', 'Domicilio', 'Para llevar'], horario: 'Lunes - Domingo: 24 horas', web: 'https://www.facebook.com/dennysguatemala/?locale=es_LA',img1:'https://a.mktgcdn.com/p/oSNPnYN4DJJcIY1dWpl5PwBqY3Mtu8niBm1b7Udcj_g/500x500.jpg',img2:'https://media-cdn.tripadvisor.com/media/photo-s/19/40/f4/ea/20190915-073939-largejpg.jpg',img3:'https://media-cdn.tripadvisor.com/media/photo-f/19/40/f4/e4/20190915-075320-largejpg.jpg'})
CREATE (Quintana_Bistrot:Restaurante {nombre: 'Quintana Bistrot', ubicacion: 'Local 16d plaza fontabella zona 10, ciudad de guatemala, 01016', precio: '39 GTQ - 272 GTQ', tipo_comida: ['Vegano', 'Vegetariano', 'Gourmet', 'Comida internacional'], ambiente: ['Familiar', 'Aire libre', 'Romantico'], tipo_servicio: ['A la mesa', 'Domicilio', 'Para llevar'], horario: ['Lunes - Jueves: 12:30 pm - 22:00 pm', 'Viernes - Sabado: 12:30 pm - 23:00 pm', 'Domingo: 10:30 am - 19:00 pm'], web: 'https://www.facebook.com/Quintanabistrot',img1:'https://media-cdn.tripadvisor.com/media/photo-s/18/ab/66/b6/excelente-restaurante.jpg',img2:'https://media-cdn.tripadvisor.com/media/photo-s/0d/9c/9b/ab/contamos-con-mezzanine.jpg',img3:'https://media-cdn.tripadvisor.com/media/photo-s/1d/8d/85/ea/munchies-delicado-postre.jpg'})
CREATE (Gracia_Cocina_de_Autor:Restaurante {nombre: 'Gracia Cocina de Autor', ubicacion: '6 Avenida 13-01 Zona 10 Zona 10, Plaza Diez, Segundo Nivel, Ciudad de Guatemala 01010 Guatemala', precio: '48 GTQ - 295 GTQ', tipo_comida: ['Comida internacional', 'Gourmet', 'Vegetariano'], ambiente: ['Familiar', 'Romantico', 'Aire libre', 'Negocios'], tipo_servicio: ['A la mesa', 'Bar'], horario: ['Lunes - Miercoles: 12:00 pm - 22:00 pm', 'Jueves: 12:00pm - 22:30 pm, Viernes: 12:00 pm - 23:00 pm', 'Sabado: 10:00 am - 23:00 pm', 'Domingo: 9:00 am - 17:00 pm'], web: 'https://www.facebook.com/graciacocinadeautor/',img1:'https://media-cdn.tripadvisor.com/media/photo-p/10/aa/ba/3f/img-20170914-204029-156.jpg',img2:'https://media-cdn.tripadvisor.com/media/photo-s/05/f9/0d/45/catering-gracia-cocinadeautor.jpg',img3:'https://media-cdn.tripadvisor.com/media/photo-s/05/e3/2d/ed/lomito-foie.jpg'})
CREATE (Applebees:Restaurante {nombre: 'Applebees', ubicacion: ['Zona Viva, 2a. Avenida 12-55, Zona 10, Guatemala', 'Centro Comercial Portales, 2 Nivel Local L-235, zona 17.'], precio: '21 GTQ - 139 GTQ', tipo_comida: ['Bar', 'Comida internacional', 'Infantil'], ambiente: ['Familiar'], tipo_servicio: ['Domicilio', 'A la mesa', 'Bar'], horario: 'Lunes - Domingo 7:00 am - 21:00 pm', web: 'http://www.applebees.com.gt/',img1:'https://www.applebees.com.gt/images/menu/Home_CelebrationPacks.jpg',img2:'https://media-cdn.tripadvisor.com/media/photo-s/0d/38/a8/b2/photo1jpg.jpg',img3:'https://media-cdn.tripadvisor.com/media/photo-s/02/be/c0/a4/applebee-s.jpg'})
CREATE (El_Portalito:Restaurante {nombre: 'El Portalito', ubicacion: 'Avenida y 9A calle z.1 Ciudad de Guatemala 6A Interior del pasaje Rubio, Ciudad de Guatemala 01001 Guatemala', precio: '25 GTQ - 135 GTQ', tipo_comida: ['Comida de mar', 'Vegetariano', 'Saludable', 'Infantil', 'Comida internacional'], ambiente: ['Familiar', 'Aire libre'], tipo_servicio: ['A la mesa', 'Bar'], horario: ['Lunes - Sabado: 10:30 am - 21:30 pm','Domingo: Cerrado'], web: 'https://www.facebook.com/people/El-Portalito/100069125873073/?locale=es_LA',img1:'https://www.guatemala.com/fotos/2021/09/El-Portalito-restaurante.jpg',img2:'https://www.guatemala.com/fotos/2021/09/El-Portalito-el-primer-bar-que-existio-Guatemala.jpg',img3:'https://4.bp.blogspot.com/-X4ure77M_Jw/Vyu-KcJtbZI/AAAAAAAABB8/P46i6rHpCgwtRe7VNppgBQmNQngQCpIBwCLcB/s1600/ElPortalito.JPG'})
CREATE (Los_Cebollines:Restaurante {nombre: 'Los Cebollines', ubicacion: ['12va Calle, 7ma Avenida, 6-17 - Zona 9 - Guatemala', 'Avenida Las Americas, 6-69 cc. Parque Las Americas Local 108 - Zona 14 - Guatemala'], precio: '30 GTQ - 315 GTQ', tipo_comida: ['Comida internacional', 'Guatemalteca', 'Infantil'], ambiente: ['Familiar', 'Aire libre'], tipo_servicio: ['A la mesa', 'Para llevar', 'Domicilio'], horario: 'Lunes - Domingo 6:30 am - 21:00 pm', web: 'https://cebollines.com/',img1:'https://media-cdn.tripadvisor.com/media/photo-s/08/9c/77/94/los-cebollines-restaurante.jpg',img2:'https://fastly.4sqi.net/img/general/200x200/29807164_BiSl1ZsgZYtsdPdNqYwtLBo26ZhA-6vTwDtoEavtlSk.jpg',img3:'https://cebollines.com/images/website/76d2541b0f6d1caeea26f71f4b51432d.jpeg'})
CREATE (Sushi_Itto:Restaurante {nombre: 'Sushi Itto', ubicacion: ['26 avenida 26-50 zona 11, via Majadas', 'Blvd San Cristobal entre 5a. avenida y 6a avenida, 3-05, Sector A-3, zona 8, San Cristobal 1'], precio: '20 GTQ - 790 GTQ', tipo_comida: ['Comida de mar', 'Comida internacional'], ambiente: ['Familiar', 'Aire libre'], tipo_servicio: ['A la mesa', 'Para llevar', 'Domicilio'], horario: ['Lunes - Jueves: 12:00 pm - 23:00 pm', 'Viernes - Domingo: 12:00 pm - 23:45 pm'], web: 'https://www.sushiitto.com.gt/index.php',img1:'https://www.sushiitto.com.gt/assets/img/restaurants/Sushiitto-La-Estaci%C3%B3n-zon-10.jpg',img2:'https://i.pinimg.com/564x/88/50/91/8850918cfd51f75f1db30f89a22c60ae.jpg',img3:'https://i.pinimg.com/564x/20/c9/69/20c969742e02173af81ae26ea9e395ab.jpg'})
CREATE (Hacienda_Real:Restaurante {nombre: 'Hacienda Real', ubicacion: '5ta. Avenida 14-67 Zona 10, Ciudad de Guatemala 01010 Guatemala', precio: '78 GTQ - 195 GTQ', tipo_comida: ['Comida internacional', 'Saludable', 'Comida de mar', 'Guatemalteca'], ambiente: ['Negocios', 'Familiar', 'Aire libre', 'Negocios', 'Romantico'], tipo_servicio: ['Bar', 'A la mesa', 'Para llevar', 'Domicilio'], horario: ['Lunes - Martes: 12:00 pm - 23:00 pm','Miercoles - Sabado: 12:00 pm - 23:59 pm','Domingo: 12:00 pm - 22:00 pm'], web: 'https://haciendareal.net/',img1:'https://www.guatemala.com/fotos/2021/05/Hacienda-Real-abrio-nuevo-restaurante-en-Etu-Plaza-Ciudad-de-Guatemala4-885x500.jpg',img2:'https://media-cdn.tripadvisor.com/media/photo-s/1a/b9/d7/e7/platillo-de-entrana.jpg',img3:'https://media-cdn.tripadvisor.com/media/photo-f/0b/b9/0f/c6/nuevas-ensaladas.jpg'})
CREATE (Casa_Chapina:Restaurante {nombre: 'Casa Chapina', ubicacion: '1 avenida 13-42 zona 10, Guatemala City, Guatemala', precio: '8 GTQ - 195 GTQ', tipo_comida: ['Infantil', 'Guatemalteca'], ambiente: 'Familiar', tipo_servicio: ['A la mesa', 'Para llevar', 'Domicilio'], horario: ['Lunes - Sabado: 8:00 am - 22:00 pm','Domingo: 8:00 am - 21:00 pm'],web: 'https://m.facebook.com/people/Casa-Chapina/100063486072976/?locale=es_LA',img1:'https://s3-media0.fl.yelpcdn.com/bphoto/Ym6OgFHOBbeyWRIi8P1iWw/o.jpg',img2:'https://fastly.4sqi.net/img/general/width960/11871903_ROFemFARkkCA4lmyv429twWDDvH8A8_K3GYA_perQnM.jpg',img3:'https://fastly.4sqi.net/img/general/width960/61565938_zC_-O35PzU8rF7Q7fd7EGknQp-kF5nY2Abn5Tt3SR_U.jpg'})
CREATE (Los_Tres_Tiempos:Restaurante {nombre: 'Los Tres Tiempos', ubicacion: '6 Av A10-13 Zona 1 Nivel 11 del Edificio Centro Vivo, Ciudad de Guatemala 01001 Guatemala', precio: '43 GTQ - 289 GTQ', tipo_comida: ['Infantil', 'Guatemalteca', 'Comida internacional'], ambiente: ['Vistas', 'Aire libre', 'Familiar', 'Romantico', 'Vistas'], tipo_servicio: ['A la mesa', 'Para llevar', 'Domicilio', 'Bar'], horario: ['Lunes - Martes: 8:00 am - 21:00 pm','Miercoles - Jueves: 8:00 am - 22:00 pm','Viernes - Sabado: 8:00 am - 23:00 pm', 'Domingo: 8:00 am - 20:00 pm'], web: 'https://www.lostrestiempos.com/',img1:'https://dea154aeb528bee620f5-799733fd03b9298a9f65fee6178f3d08.ssl.cf1.rackcdn.com/pix_16_100199_39268_62e741a734cea.jpg',img2:'https://dea154aeb528bee620f5-799733fd03b9298a9f65fee6178f3d08.ssl.cf1.rackcdn.com/pix_16_100199_36704_61df46f5ef3a1.jpg',img3:'https://www.guatemala.com/fotos/2021/09/Los-Tres-Tiempos-la-terraza-con-vista-panoramica-al-Centro-Historico-885x500.jpg'})
CREATE (Los_Ranchos:Restaurante {nombre: 'Los Ranchos', ubicacion: ['12 Calle, 02 25 Zona 10 Edificio AVIA 3er Nivel, Ciudad de Guatemala 01010 Guatemala', 'Miraflores, 21 avenida 4-32, zona 11 nivel 1'], precio: '117 GTQ - 234 GTQ', tipo_comida: ['Comida internacional', 'Comida de mar', 'Vegetariano', 'Infantil', 'Saludable'], ambiente: ['Aire libre', 'Familiar'], tipo_servicio: ['A la mesa', 'Para llevar'], horario: ['Lunes - Viernes: 12:00 pm - 22:00 pm', 'Sabado - Domingo: 8:00 am - 22:00 pm'], web: 'https://losranchos.com.gt/',img1:'https://media-cdn.tripadvisor.com/media/photo-s/14/59/35/86/nuestra-barra.jpg',img2:'https://dea154aeb528bee620f5-799733fd03b9298a9f65fee6178f3d08.ssl.cf1.rackcdn.com/pix_16_284_2000_5f850b24aaeb6.jpg',img3:'https://media-cdn.tripadvisor.com/media/photo-f/14/59/88/45/hamburguesa-con-queso.jpg'})
CREATE (Jakes:Restaurante {nombre: 'Jakes', ubicacion: '8a Avenida 16-70, Zona 10 Centro Comercial La Estacion, Ciudad de Guatemala 01010 Guatemala', precio: '55 GTQ - 495 GTQ', tipo_comida: ['Gourmet', 'Comida internacional', 'Comida de mar'], ambiente: ['Aire libre', 'Vistas', 'Negocios', 'Familiar', 'Romantico'], tipo_servicio: ['A la mesa', 'Para llevar', 'Domicilio', 'Bar'], horario: ['Lunes: 12:00 pm - 21:00 pm', 'Martes - Viernes: 12:00 pm - 22:30 pm', 'Sabados: 9:30 am - 22:30 pm', 'Domingo: 9:30 am - 15:00 pm'], web: 'https://jakesathome.com/',img1:'https://www.guatemala.com/fotos/201709/Jakes-Restaurante-885x500.jpg',img2:'https://cdn.shopify.com/s/files/1/0277/4171/6544/products/filet_392da3b1-cc23-46e6-8a7a-8888cb7e6629_590x.png?v=1621366358',img3:'https://cdn.shopify.com/s/files/1/0277/4171/6544/products/Ossobuco_900x.png?v=1590792020'})
CREATE (Pollo_Campero:Restaurante {nombre: 'Pollo Campero', ubicacion: ['Centro Comercial Galerias Primma, Calzada Roosevelt 13-46, Guatemala, 01007', 'Centro Comercial Prisa, 10a Avenida, Guatemala, Guatemala 01010'], precio: '33 GTQ - 175 GTQ', tipo_comida: ['Comida internacional', 'Infantil'], ambiente: ['Aire libre', 'Familiar'], tipo_servicio: ['A la mesa', 'Para llevar', 'Domicilio'], horario: 'Lunes - Domingo: 5:30 am - 21:30 pm', web: 'https://gt.campero.com/home',img1:'https://global-uploads.webflow.com/5e34767f6a3a0e8257cafc5c/64076288c84f4000d7cd3fac_20pc_meal_with_sides.jpg',img2:'https://media-cdn.tripadvisor.com/media/photo-s/14/65/12/06/fb-img-1535658078694.jpg',img3:'https://www.cmi.co/media/k2/items/cache/df1da44862bfbe0dd2169e4d14570593_XL.jpg'})
CREATE (Kacao:Restaurante {nombre: 'Kacao', ubicacion: '2a Avenida 13-44 Zona 10, Guatemala City, Guatemala', precio: '62 GTQ - 350 GTQ', tipo_comida: ['Comida internacional', 'Guatemalteca'], ambiente: ['Aire libre', 'Familiar', 'Vistas', 'Entretenimiento'], tipo_servicio: ['Bar', 'A la mesa', 'Para llevar', 'Domicilio'], horario: ['Lunes: 12:00 pm - 22:30 pm', 'Martes - Sabado: 12:00 pm - 23:00 pm', 'Domingo: 12:00 pm - 22:00 pm'], web: 'https://www.facebook.com/Kacao.Maya/?locale=es_LA',img1:'https://media-cdn.tripadvisor.com/media/photo-s/0d/18/7f/b1/20160924-203414-largejpg.jpg',img2:'https://scontent.fgua3-3.fna.fbcdn.net/v/t31.18172-8/903851_632028936822979_191643211_o.jpg?_nc_cat=108&ccb=1-7&_nc_sid=9267fe&_nc_ohc=sOZg9zGpv50AX-nv86p&_nc_ht=scontent.fgua3-3.fna&oh=00_AfCUW4to2lowUG_-vsAuEdbRXYJCux9Cxu_yVnD9Qv3c_g&oe=6498DCEE',img3:'https://scontent.fgua3-4.fna.fbcdn.net/v/t31.18172-8/892164_618060604886479_1564637907_o.jpg?_nc_cat=100&ccb=1-7&_nc_sid=e3f864&_nc_ohc=86v_rnq07fkAX_S2Dy1&_nc_oc=AQloJkNksxbp-q1hlDJroYSpNHI0t7gTW2ST-I4cK1oVjrHVUZtUjLHX86WNtFEtp8U&_nc_ht=scontent.fgua3-4.fna&oh=00_AfAgq1l_EvwlPm_sxXf-eMJAycFdlDVXmaOjIVTsEbcHgg&oe=6498DB79'})
CREATE (Altuna:Restaurante {nombre: 'Altuna', ubicacion: 'C5A Avenida 12-31, Cdad. de Guatemala 01001 Blvr. Rafael Landivar 10-05, Cdad. de Guatemala', precio: '41 GTQ - 225 GTQ', tipo_comida: ['Comida internacional', 'Comida del mar'], ambiente: ['Aire libre', 'Vistas', 'Negocios', 'Familiar', 'Romantico'], tipo_servicio: ['Bar', 'A la mesa', 'Para llevar', 'Domicilio'], horario: ['Lunes: 12:00 pm - 17:00 pm','Martes - Sabado: 12:00 pm 22:30 pm' ,'Domingo: 12:00 pm - 17:00 pm'], web: 'https://www.facebook.com/restaurantealtuna/?locale=es_LA',img1:'https://media-cdn.tripadvisor.com/media/photo-p/12/f7/cc/26/photo6jpg.jpg',img2:'https://5dc93791f535c5b6680b-504f722ff1ef8102127dae26bdb15aa6.ssl.cf1.rackcdn.com/pix_16_427_2665_62d39b20c9775.jpg',img3:'https://5dc93791f535c5b6680b-504f722ff1ef8102127dae26bdb15aa6.ssl.cf1.rackcdn.com/pix_16_427_24911_621a804bc88a9.jpg'})

CREATE (zona_9:zona {zona:'9'})
CREATE (zona_10:zona {zona:'10'})
CREATE (zona_7:zona {zona:'7'})
CREATE (zona_4:zona {zona:'4'})
CREATE (zona_11:zona {zona:'11'})
CREATE (zona_12:zona {zona:'12'})
CREATE (zona_15:zona {zona:'15'})
CREATE (zona_17:zona {zona:'17'})
CREATE (zona_1:zona {zona:'1'})
CREATE (zona_14:zona {zona:'14'})
CREATE (zona_8:zona {zona:'8'})
CREATE (zona_16:zona {zona:'16'})

CREATE (precio_gama_alta:precio {precio:'Gama alta'})
CREATE (precio_promedio:precio {precio:'Promedio'})
CREATE (precio_economico:precio {precio:'Economico'})

CREATE(Guatemalteca:Tipo_comida{tipo_comida:"Guatemalteca"})
CREATE(Comida_internacional:Tipo_comida{tipo_comida:"Comida internacional"})
CREATE(Comida_rapida:Tipo_comida{tipo_comida:"Comida rapida"})
CREATE(Vegetariano:Tipo_comida{tipo_comida:"Vegetariano"})
CREATE(Vegano:Tipo_comida{tipo_comida:"Vegano"})
CREATE(Saludable:Tipo_comida{tipo_comida:"Saludable"})
CREATE(Comida_de_mar:Tipo_comida{tipo_comida:"Comida de mar"})
CREATE(Infantil:Tipo_comida{tipo_comida:"Infantil"})
CREATE(Bar:Tipo_comida{tipo_comida:"Bar"})
CREATE(Gourmet:Tipo_comida{tipo_comida:"Gourmet"})

CREATE (Romantico:Ambiente {ambiente:'Romantico'})
CREATE (Familiar:Ambiente {ambiente:'Familiar'})
CREATE (Negocios:Ambiente {ambiente:'Negocios'})
CREATE (Vistas:Ambiente {ambiente:'Vistas'})
CREATE (Entretenimiento:Ambiente {ambiente:'Entretenimiento'})
CREATE (Aire_libre:Ambiente {ambiente:'Aire libre'})

CREATE (para_llevar:tipo_servicio {tipo_servicio: 'Para llevar'})
CREATE (domicilio:tipo_servicio {tipo_servicio: 'Domicilio'})
CREATE (bufet:tipo_servicio {tipo_servicio: 'Bufet'})
CREATE (a_la_mesa:tipo_servicio {tipo_servicio: 'A la mesa'})
CREATE (bar:tipo_servicio {tipo_servicio: 'Bar'})

CREATE (Desayuno:Horario {Horario: 'Desayuno'})
CREATE (Almuerzo:Horario {Horario: 'Almuerzo'})
CREATE (Cena:Horario {Horario: 'Cena'})
CREATE (Brunch:Horario {Horario: 'Brunch'})
CREATE (Happy_hour:Horario {Horario: 'Happy hour'})
CREATE (_24_horas:Horario {Horario: '24 horas'})
CREATE (Fines_de_semana:Horario {Horario: 'Fines de Semana'})


WITH Rincon_del_Steak, Cadejo_Brewing_Company_Beerhouse_and_Grill, Restaurante_El_Cafetal,
En_Un_Dos_Por_Crepes, _100_montaditos, Baoz, Carpaccio_Restaurante, 
Pronto_Pizza, Pizza_Vesuvio, Dennys, Quintana_Bistrot, Gracia_Cocina_de_Autor, 
Applebees, El_Portalito, Los_Cebollines, Sushi_Itto, Hacienda_Real, Casa_Chapina, 
Los_Tres_Tiempos, Los_Ranchos, Jakes, Pollo_Campero, Kacao, Altuna, zona_9, zona_10, 
zona_7, zona_4, zona_11, zona_12, zona_15, zona_17, zona_1, zona_14, zona_8, zona_16,
precio_gama_alta, precio_promedio, precio_economico,Guatemalteca, Comida_internacional, Comida_rapida, Vegetariano, Vegano, Saludable, 
Comida_de_mar, Infantil, Bar, Gourmet,Romantico, Familiar, Negocios, Vistas, Entretenimiento, Aire_libre
,para_llevar, domicilio, bufet, a_la_mesa, bar
,Desayuno, Almuerzo, Cena, Brunch, Happy_hour, _24_horas, Fines_de_semana



CREATE (Rincon_del_Steak)-[:Ubicacion]->(zona_10)
CREATE (Cadejo_Brewing_Company_Beerhouse_and_Grill)-[:Ubicacion]->(zona_9)
CREATE (En_Un_Dos_Por_Crepes)-[:Ubicacion]->(zona_10)
CREATE (_100_montaditos)-[:Ubicacion]->(zona_7)
CREATE (_100_montaditos)-[:Ubicacion]->(zona_11)
CREATE (Baoz)-[:Ubicacion]->(zona_4)
CREATE (Baoz)-[:Ubicacion]->(zona_12)
CREATE (Restaurante_El_Cafetal)-[:Ubicacion]->(zona_9)
CREATE (Carpaccio_Restaurante)-[:Ubicacion]->(zona_10)
CREATE (Pronto_Pizza)-[:Ubicacion]->(zona_11)
CREATE (Pizza_Vesuvio)-[:Ubicacion]->(zona_4)
CREATE (Pizza_Vesuvio)-[:Ubicacion]->(zona_15)
CREATE (Dennys)-[:Ubicacion]->(zona_9)
CREATE (Dennys)-[:Ubicacion]->(zona_15)
CREATE (Quintana_Bistrot)-[:Ubicacion]->(zona_10)
CREATE (Gracia_Cocina_de_Auto)-[:Ubicacion]->(zona_10)
CREATE (Applebees)-[:Ubicacion]->(zona_10)
CREATE (Applebees)-[:Ubicacion]->(zona_17)
CREATE (El_Portalito)-[:Ubicacion]->(zona_1)
CREATE (Los_Cebollines)-[:Ubicacion]->(zona_9)
CREATE (Los_Cebollines)-[:Ubicacion]->(zona_14)
CREATE (Sushi_Itto)-[:Ubicacion]->(zona_11)
CREATE (Sushi_Itto)-[:Ubicacion]->(zona_8)
CREATE (Hacienda_Real)-[:Ubicacion]->(zona_10)
CREATE (Casa_Chapina)-[:Ubicacion]->(zona_10)
CREATE (Los_Tres_Tiempos)-[:Ubicacion]->(zona_1)
CREATE (Los_Ranchos)-[:Ubicacion]->(zona_10)
CREATE (Los_Ranchos)-[:Ubicacion]->(zona_11)
CREATE (Jakes)-[:Ubicacion]->(zona_10)
CREATE (Pollo_Campero)-[:Ubicacion]->(zona_7)
CREATE (Pollo_Campero)-[:Ubicacion]->(zona_10)
CREATE (Kacao)-[:Ubicacion]->(zona_10)
CREATE (Altuna)-[:Ubicacion]->(zona_1)
CREATE (Altuna)-[:Ubicacion]->(zona_16)

CREATE (Rincon_del_Steak)-[:Precio]->(precio_gama_alta)
CREATE (Cadejo_Brewing_Company_Beerhouse_and_Grill)-[:Precio]->(precio_promedio)
CREATE (En_Un_Dos_Por_Crepes)-[:Precio]->(precio_economico)
CREATE (_100_montaditos)-[:Precio]->(precio_promedio)
CREATE (Baoz)-[:Precio]->(precio_economico)
CREATE (Restaurante_El_Cafetal)-[:Precio]->(precio_gama_alta)
CREATE (Carpaccio_Restaurante)-[:Precio]->(precio_gama_alta)
CREATE (Pronto_Pizza)-[:Precio]->(precio_promedio)
CREATE (Pizza_Vesuvio)-[:Precio]->(precio_promedio)
CREATE (Dennys)-[:Precio]->(precio_promedio)
CREATE (Quintana_Bistrot)-[:Precio]->(precio_gama_alta)
CREATE (Gracia_Cocina_de_Autor)-[:Precio]->(precio_gama_alta)
CREATE (Applebees)-[:Precio]->(precio_promedio)
CREATE (El_Portalito)-[:Precio]->(precio_promedio)
CREATE (Los_Cebollines)-[:Precio]->(precio_promedio)
CREATE (Sushi_Itto)-[:Precio]->(precio_promedio)
CREATE (Sushi_Itto)-[:Precio]->(precio_gama_alta)
CREATE (Hacienda_Real)-[:Precio]->(precio_gama_alta)
CREATE (Casa_Chapina)-[:Precio]->(precio_economico)
CREATE (Casa_Chapina)-[:Precio]->(precio_promedio)
CREATE (Los_Tres_Tiempos)-[:Precio]->(precio_gama_alta)
CREATE (Los_Ranchos)-[:Precio]->(precio_gama_alta)
CREATE (Jakes)-[:Precio]->(precio_gama_alta)
CREATE (Pollo_Campero)-[:Precio]->(precio_economico)
CREATE (Kacao)-[:Precio]->(precio_gama_alta)
CREATE (Kacao)-[:Precio]->(precio_promedio)
CREATE (Altuna)-[:Precio]->(precio_promedio)

CREATE (Rincon_del_Steak)-[:Tipo_Comida]->(Comida_internacional)
CREATE (Rincon_del_Steak)-[:Tipo_Comida]->(Comida_de_mar)
CREATE (Cadejo_Brewing_Company_Beerhouse_and_Grill)-[:Tipo_Comida]->(Vegano)
CREATE (Cadejo_Brewing_Company_Beerhouse_and_Grill)-[:Tipo_Comida]->(Vegetariano)
CREATE (Cadejo_Brewing_Company_Beerhouse_and_Grill)-[:Tipo_Comida]->(Bar)
CREATE (Cadejo_Brewing_Company_Beerhouse_and_Grill)-[:Tipo_Comida]->(Comida_de_mar)
CREATE (En_Un_Dos_Por_Crepes)-[:Tipo_Comida]->(Comida_internacional)
CREATE (_100_montaditos)-[:Tipo_Comida]->(Comida_internacional)
CREATE (_100_montaditos)-[:Tipo_Comida]->(Vegetariano)
CREATE (Baoz)-[:Tipo_Comida]->(Comida_internacional)
CREATE (Restaurante_El_Cafetal)-[:Tipo_Comida]->(Comida_internacional)
CREATE (Restaurante_El_Cafetal)-[:Tipo_Comida]->(Vegano)
CREATE (Restaurante_El_Cafetal)-[:Tipo_Comida]->(Vegetariano)
CREATE (Restaurante_El_Cafetal)-[:Tipo_Comida]->(Gourmet)
CREATE (Restaurante_El_Cafetal)-[:Tipo_Comida]->(Infantil)
CREATE (Carpaccio_Restaurante)-[:Tipo_Comida]->(Comida_internacional)
CREATE (Carpaccio_Restaurante)-[:Tipo_Comida]->(Vegetariano)
CREATE (Carpaccio_Restaurante)-[:Tipo_Comida]->(Bar)
CREATE (Carpaccio_Restaurante)-[:Tipo_Comida]->(Gourmet)
CREATE (Carpaccio_Restaurante)-[:Tipo_Comida]->(Comida_de_mar)
CREATE (Pronto_Pizza)-[:Tipo_Comida]->(Comida_rapida)
CREATE (Pizza_Vesuvio)-[:Tipo_Comida]->(Comida_internacional)
CREATE (Pizza_Vesuvio)-[:Tipo_Comida]->(Bar)
CREATE (Pizza_Vesuvio)-[:Tipo_Comida]->(Vegetariano)
CREATE (Dennys)-[:Tipo_Comida]->(Comida_internacional)
CREATE (Dennys)-[:Tipo_Comida]->(Vegetariano)
CREATE (Dennys)-[:Tipo_Comida]->(Infantil)
CREATE (Dennys)-[:Tipo_Comida]->(Saludable)
CREATE (Quintana_Bistrot)-[:Tipo_Comida]->(Vegetariano)
CREATE (Quintana_Bistrot)-[:Tipo_Comida]->(Vegano)
CREATE (Quintana_Bistrot)-[:Tipo_Comida]->(Gourmet)
CREATE (Quintana_Bistrot)-[:Tipo_Comida]->(Comida_internacional)
CREATE (Gracia_Cocina_de_Autor)-[:Tipo_Comida]->(Comida_internacional)
CREATE (Gracia_Cocina_de_Autor)-[:Tipo_Comida]->(Gourmet)
CREATE (Gracia_Cocina_de_Autor)-[:Tipo_Comida]->(Vegetariano)
CREATE (Applebees)-[:Tipo_Comida]->(Bar)
CREATE (Applebees)-[:Tipo_Comida]->(Comida_internacional)
CREATE (Applebees)-[:Tipo_Comida]->(Infantil)
CREATE (El_Portalito)-[:Tipo_Comida]->(Comida_de_mar)
CREATE (El_Portalito)-[:Tipo_Comida]->(Vegetariano)
CREATE (El_Portalito)-[:Tipo_Comida]->(Saludable)
CREATE (El_Portalito)-[:Tipo_Comida]->(Infantil)
CREATE (El_Portalito)-[:Tipo_Comida]->(Comida_internacional)
CREATE (Los_Cebollines)-[:Tipo_Comida]->(Comida_internacional)
CREATE (Los_Cebollines)-[:Tipo_Comida]->(Guatemalteca)
CREATE (Los_Cebollines)-[:Tipo_Comida]->(Infantil)
CREATE (Sushi_Itto)-[:Tipo_Comida]->(Comida_internacional)
CREATE (Sushi_Itto)-[:Tipo_Comida]->(Comida_de_mar)
CREATE (Hacienda_Real)-[:Tipo_Comida]->(Comida_internacional)
CREATE (Hacienda_Real)-[:Tipo_Comida]->(Saludable)
CREATE (Hacienda_Real)-[:Tipo_Comida]->(Comida_de_mar)
CREATE (Hacienda_Real)-[:Tipo_Comida]->(Guatemalteca)
CREATE (Casa_Chapina)-[:Tipo_Comida]->(Guatemalteca)
CREATE (Casa_Chapina)-[:Tipo_Comida]->(Infantil)
CREATE (Los_Tres_Tiempos)-[:Tipo_Comida]->(Guatemalteca)
CREATE (Los_Tres_Tiempos)-[:Tipo_Comida]->(Comida_internacional)
CREATE (Los_Tres_Tiempos)-[:Tipo_Comida]->(Infantil)
CREATE (Los_Ranchos)-[:Tipo_Comida]->(Comida_internacional)
CREATE (Los_Ranchos)-[:Tipo_Comida]->(Comida_de_mar)
CREATE (Los_Ranchos)-[:Tipo_Comida]->(Vegetariano)
CREATE (Los_Ranchos)-[:Tipo_Comida]->(Infantil)
CREATE (Los_Ranchos)-[:Tipo_Comida]->(Saludable)
CREATE (Jakes)-[:Tipo_Comida]->(Gourmet)
CREATE (Jakes)-[:Tipo_Comida]->(Comida_internacional)
CREATE (Jakes)-[:Tipo_Comida]->(Comida_de_mar)
CREATE (Pollo_Campero)-[:Tipo_Comida]->(Infantil)
CREATE (Pollo_Campero)-[:Tipo_Comida]->(Comida_internacional)
CREATE (Kacao)-[:Tipo_Comida]->(Guatemalteca)
CREATE (Kacao)-[:Tipo_Comida]->(Comida_internacional)
CREATE (Altuna)-[:Tipo_Comida]->(Comida_internacional)
CREATE (Altuna)-[:Tipo_Comida]->(Comida_de_mar)

CREATE (Rincon_del_Steak)-[:Ambiente]->(Familiar)
CREATE (Rincon_del_Steak)-[:Ambiente]->(Romantico)
CREATE (Rincon_del_Steak)-[:Ambiente]->(Negocios)
CREATE (Cadejo_Brewing_Company_Beerhouse_and_Grill)-[:Ambiente]->(Familiar)
CREATE (Cadejo_Brewing_Company_Beerhouse_and_Grill)-[:Ambiente]->(Aire_libre)
CREATE (Cadejo_Brewing_Company_Beerhouse_and_Grill)-[:Ambiente]->(Entretenimiento)
CREATE (En_Un_Dos_Por_Crepes)-[:Ambiente]->(Familiar)
CREATE (En_Un_Dos_Por_Crepes)-[:Ambiente]->(Aire_libre)
CREATE (_100_montaditos)-[:Ambiente]->(Familiar)
CREATE (Baoz)-[:Ambiente]->(Familiar)
CREATE (Restaurante_El_Cafetal)-[:Ambiente]->(Familiar)
CREATE (Restaurante_El_Cafetal)-[:Ambiente]->(Negocios)
CREATE (Restaurante_El_Cafetal)-[:Ambiente]->(Romantico)
CREATE (Carpaccio_Restaurante)-[:Ambiente]->(Familiar)
CREATE (Carpaccio_Restaurante)-[:Ambiente]->(Romantico)
CREATE (Carpaccio_Restaurante)-[:Ambiente]->(Aire_libre)
CREATE (Carpaccio_Restaurante)-[:Ambiente]->(Negocios)
CREATE (Pronto_Pizza)-[:Ambiente]->(Familiar)
CREATE (Pronto_Pizza)-[:Ambiente]->(Aire_libre)
CREATE (Pizza_Vesuvio)-[:Ambiente]->(Aire_libre)
CREATE (Pizza_Vesuvio)-[:Ambiente]->(Familiar)
CREATE (Dennys)-[:Ambiente]->(Familiar)
CREATE (Quintana_Bistrot)-[:Ambiente]->(Familiar)
CREATE (Quintana_Bistrot)-[:Ambiente]->(Romantico)
CREATE (Quintana_Bistrot)-[:Ambiente]->(Aire_libre)
CREATE (Gracia_Cocina_de_Autor)-[:Ambiente]->(Familiar)
CREATE (Gracia_Cocina_de_Autor)-[:Ambiente]->(Negocios)
CREATE (Gracia_Cocina_de_Autor)-[:Ambiente]->(Romantico)
CREATE (Gracia_Cocina_de_Autor)-[:Ambiente]->(Aire_libre)
CREATE (Applebees)-[:Ambiente]->(Familiar)
CREATE (El_Portalito)-[:Ambiente]->(Familiar)
CREATE (El_Portalito)-[:Ambiente]->(Aire_libre)
CREATE (Los_Cebollines)-[:Ambiente]->(Aire_libre)
CREATE (Los_Cebollines)-[:Ambiente]->(Familiar)
CREATE (Sushi_Itto)-[:Ambiente]->(Aire_libre)
CREATE (Sushi_Itto)-[:Ambiente]->(Familiar)
CREATE (Hacienda_Real)-[:Ambiente]->(Romantico)
CREATE (Hacienda_Real)-[:Ambiente]->(Familiar)
CREATE (Hacienda_Real)-[:Ambiente]->(Aire_libre)
CREATE (Hacienda_Real)-[:Ambiente]->(Negocios)
CREATE (Casa_Chapina)-[:Ambiente]->(Familiar)
CREATE (Los_Tres_Tiempos)-[:Ambiente]->(Vistas)
CREATE (Los_Tres_Tiempos)-[:Ambiente]->(Aire_libre)
CREATE (Los_Tres_Tiempos)-[:Ambiente]->(Familiar)
CREATE (Los_Tres_Tiempos)-[:Ambiente]->(Romantico)
CREATE (Los_Ranchos)-[:Ambiente]->(Familiar)
CREATE (Los_Ranchos)-[:Ambiente]->(Aire_libre)
CREATE (Jakes)-[:Ambiente]->(Romantico)
CREATE (Jakes)-[:Ambiente]->(Familiar)
CREATE (Jakes)-[:Ambiente]->(Negocios)
CREATE (Jakes)-[:Ambiente]->(Vistas)
CREATE (Jakes)-[:Ambiente]->(Aire_libre)
CREATE (Pollo_Campero)-[:Ambiente]->(Aire_libre)
CREATE (Pollo_Campero)-[:Ambiente]->(Familiar)
CREATE (Kacao)-[:Ambiente]->(Familiar)
CREATE (Kacao)-[:Ambiente]->(Aire_libre)
CREATE (Kacao)-[:Ambiente]->(Entretenimiento)
CREATE (Kacao)-[:Ambiente]->(Vistas)
CREATE (Altuna)-[:Ambiente]->(Vistas)
CREATE (Altuna)-[:Ambiente]->(Aire_libre)
CREATE (Altuna)-[:Ambiente]->(Negocios)
CREATE (Altuna)-[:Ambiente]->(Familiar)
CREATE (Altuna)-[:Ambiente]->(Romantico)

CREATE (Rincon_del_Steak)-[:Tipo_Servicio]->(domicilio)
CREATE (Rincon_del_Steak)-[:Tipo_Servicio]->(a_la_mesa)
CREATE (Rincon_del_Steak)-[:Tipo_Servicio]->(para_llevar)
CREATE (Rincon_del_Steak)-[:Tipo_Servicio]->(bar)
CREATE (Cadejo_Brewing_Company_Beerhouse_and_Grill)-[:Tipo_Servicio]->(a_la_mesa)
CREATE (Cadejo_Brewing_Company_Beerhouse_and_Grill)-[:Tipo_Servicio]->(para_llevar)
CREATE (Cadejo_Brewing_Company_Beerhouse_and_Grill)-[:Tipo_Servicio]->(domicilio)
CREATE (En_Un_Dos_Por_Crepes)-[:Tipo_Servicio]->(para_llevar)
CREATE (En_Un_Dos_Por_Crepes)-[:Tipo_Servicio]->(domicilio)
CREATE (En_Un_Dos_Por_Crepes)-[:Tipo_Servicio]->(a_la_mesa)
CREATE (_100_montaditos)-[:Tipo_Servicio]->(para_llevar)
CREATE (_100_montaditos)-[:Tipo_Servicio]->(a_la_mesa)
CREATE (_100_montaditos)-[:Tipo_Servicio]->(bar)
CREATE (Baoz)-[:Tipo_Servicio]->(para_llevar)
CREATE (Baoz)-[:Tipo_Servicio]->(a_la_mesa)
CREATE (Restaurante_El_Cafetal)-[:Tipo_Servicio]->(para_llevar)
CREATE (Restaurante_El_Cafetal)-[:Tipo_Servicio]->(a_la_mesa)
CREATE (Restaurante_El_Cafetal)-[:Tipo_Servicio]->(bufet)
CREATE (Carpaccio_Restaurante)-[:Tipo_Servicio]->(a_la_mesa)
CREATE (Pronto_Pizza)-[:Tipo_Servicio]->(para_llevar)
CREATE (Pronto_Pizza)-[:Tipo_Servicio]->(domicilio)
CREATE (Pronto_Pizza)-[:Tipo_Servicio]->(para_llevar)
CREATE (Pizza_Vesuvio)-[:Tipo_Servicio]->(domicilio)
CREATE (Pizza_Vesuvio)-[:Tipo_Servicio]->(para_llevar)
CREATE (Pizza_Vesuvio)-[:Tipo_Servicio]->(a_la_mesa)
CREATE (Dennys)-[:Tipo_Servicio]->(a_la_mesa)
CREATE (Dennys)-[:Tipo_Servicio]->(para_llevar)
CREATE (Dennys)-[:Tipo_Servicio]->(domicilio)
CREATE (Quintana_Bistrot)-[:Tipo_Servicio]->(domicilio)
CREATE (Quintana_Bistrot)-[:Tipo_Servicio]->(a_la_mesa)
CREATE (Quintana_Bistrot)-[:Tipo_Servicio]->(para_llevar)
CREATE (Gracia_Cocina_de_Autor)-[:Tipo_Servicio]->(bar)
CREATE (Gracia_Cocina_de_Autor)-[:Tipo_Servicio]->(a_la_mesa)
CREATE (Applebees)-[:Tipo_Servicio]->(domicilio)
CREATE (Applebees)-[:Tipo_Servicio]->(a_la_mesa)
CREATE (Applebees)-[:Tipo_Servicio]->(bar)
CREATE (El_Portalito)-[:Tipo_Servicio]->(a_la_mesa)
CREATE (El_Portalito)-[:Tipo_Servicio]->(bar)
CREATE (Los_Cebollines)-[:Tipo_Servicio]->(para_llevar)
CREATE (Los_Cebollines)-[:Tipo_Servicio]->(a_la_mesa)
CREATE (Los_Cebollines)-[:Tipo_Servicio]->(domicilio)
CREATE (Sushi_Itto)-[:Tipo_Servicio]->(para_llevar)
CREATE (Sushi_Itto)-[:Tipo_Servicio]->(a_la_mes)
CREATE (Sushi_Itto)-[:Tipo_Servicio]->(domicilio)
CREATE (Hacienda_Real)-[:Tipo_Servicio]->(para_llevar)
CREATE (Hacienda_Real)-[:Tipo_Servicio]->(domicilio)
CREATE (Hacienda_Real)-[:Tipo_Servicio]->(a_la_mesa)
CREATE (Hacienda_Real)-[:Tipo_Servicio]->(bar)
CREATE (Casa_Chapina)-[:Tipo_Servicio]->(para_llevar)
CREATE (Casa_Chapina)-[:Tipo_Servicio]->(domicilio)
CREATE (Casa_Chapina)-[:Tipo_Servicio]->(a_la_mesa)
CREATE (Los_Tres_Tiempos)-[:Tipo_Servicio]->(domicilio)
CREATE (Los_Tres_Tiempos)-[:Tipo_Servicio]->(para_llevar)
CREATE (Los_Tres_Tiempos)-[:Tipo_Servicio]->(a_la_mesa)
CREATE (Los_Tres_Tiempos)-[:Tipo_Servicio]->(bar)
CREATE (Los_Ranchos)-[:Tipo_Servicio]->(para_llevar)
CREATE (Los_Ranchos)-[:Tipo_Servicio]->(a_la_mesa)
CREATE (Los_Ranchos)-[:Tipo_Servicio]->(bar)
CREATE (Jakes)-[:Tipo_Servicio]->(para_llevar)
CREATE (Jakes)-[:Tipo_Servicio]->(domicilio)
CREATE (Jakes)-[:Tipo_Servicio]->(a_la_mesa)
CREATE (Jakes)-[:Tipo_Servicio]->(bar)
CREATE (Pollo_Campero)-[:Tipo_Servicio]->(para_llevar)
CREATE (Pollo_Campero)-[:Tipo_Servicio]->(domicilio)
CREATE (Pollo_Campero)-[:Tipo_Servicio]->(a_la_mesa)
CREATE (Kacao)-[:Tipo_Servicio]->(para_llevar)
CREATE (Kacao)-[:Tipo_Servicio]->(domicilio)
CREATE (Kacao)-[:Tipo_Servicio]->(a_la_mesa)
CREATE (Kacao)-[:Tipo_Servicio]->(bar)
CREATE (Altuna)-[:Tipo_Servicio]->(para_llevar)
CREATE (Altuna)-[:Tipo_Servicio]->(domicilio)
CREATE (Altuna)-[:Tipo_Servicio]->(a_la_mesa)
CREATE (Altuna)-[:Tipo_Servicio]->(bar)

CREATE (Rincon_del_Steak)-[:Horario]->(Almuerzo)
CREATE (Cadejo_Brewing_Company_Beerhouse_and_Grill)-[:Horario]->(Almuerzo)
CREATE (En_Un_Dos_Por_Crepes)-[:Horario]->(Desayuno)
CREATE (En_Un_Dos_Por_Crepes)-[:Horario]->(Almuerzo)
CREATE (En_Un_Dos_Por_Crepes)-[:Horario]->(Cena)
CREATE (_100_montaditos)-[:Horario]->(Desayuno)
CREATE (_100_montaditos)-[:Horario]->(Almuerzo)
CREATE (_100_montaditos)-[:Horario]->(Cena)
CREATE (Baoz)-[:Horario]->(Almuerzo)
CREATE (Restaurante_El_Cafetal)-[:Horario]->(Desayuno)
CREATE (Restaurante_El_Cafetal)-[:Horario]->(Almuerzo)
CREATE (Restaurante_El_Cafetal)-[:Horario]->(Cena)
CREATE (Carpaccio_Restaurante)-[:Horario]->(Almuerzo)
CREATE (Carpaccio_Restaurante)-[:Horario]->(Cena)
CREATE (Pronto_Pizza)-[:Horario]->(Almuerzo)
CREATE (Pronto_Pizza)-[:Horario]->(Cena)
CREATE (Pizza_Vesuvio)-[:Horario]->(Almuerzo)
CREATE (Pizza_Vesuvio)-[:Horario]->(Cena)
CREATE (Dennys)-[:Horario]->(Desayuno)
CREATE (Dennys)-[:Horario]->(Almuerzo)
CREATE (Dennys)-[:Horario]->(Cena)
CREATE (Dennys)-[:Horario]->(_24_horas)
CREATE (Dennys)-[:Horario]->(Brunch)
CREATE (Quintana_Bistrot)-[:Horario]->(Almuerzo)
CREATE (Quintana_Bistrot)-[:Horario]->(Cena)
CREATE (Gracia_Cocina_de_Autor)-[:Horario]->(Almuerzo)
CREATE (Gracia_Cocina_de_Autor)-[:Horario]->(Cena)
CREATE (Applebees)-[:Horario]->(Desayuno)
CREATE (Applebees)-[:Horario]->(Almuerzo)
CREATE (Applebees)-[:Horario]->(Cena)
CREATE (Applebees)-[:Horario]->(Happy_hour)
CREATE (El_Portalito)-[:Horario]->(Desayuno)
CREATE (El_Portalito)-[:Horario]->(Almuerzo)
CREATE (El_Portalito)-[:Horario]->(Cena)
CREATE (Los_Cebollines)-[:Horario]->(Desayuno)
CREATE (Los_Cebollines)-[:Horario]->(Almuerzo)
CREATE (Los_Cebollines)-[:Horario]->(Cena)
CREATE (Sushi_Itto)-[:Horario]->(Almuerzo)
CREATE (Sushi_Itto)-[:Horario]->(Cena)
CREATE (Hacienda_Real)-[:Horario]->(Almuerzo)
CREATE (Hacienda_Real)-[:Horario]->(Cena)
CREATE (Casa_Chapina)-[:Horario]->(Desayuno)
CREATE (Casa_Chapina)-[:Horario]->(Almuerzo)
CREATE (Casa_Chapina)-[:Horario]->(Cena)
CREATE (Los_Tres_Tiempos)-[:Horario]->(Almuerzo)
CREATE (Los_Tres_Tiempos)-[:Horario]->(Cena)
CREATE (Los_Ranchos)-[:Horario]->(Desayuno)
CREATE (Los_Ranchos)-[:Horario]->(Almuerzo)
CREATE (Los_Ranchos)-[:Horario]->(Cena)
CREATE (Los_Ranchos)-[:Horario]->(Brunch)
CREATE (Los_Ranchos)-[:Horario]->(Fines_de_semana)
CREATE (Jakes)-[:Horario]->(Almuerzo)
CREATE (Jakes)-[:Horario]->(Cena)
CREATE (Jakes)-[:Horario]->(Brunch)
CREATE (Jakes)-[:Horario]->(Fines_de_semana)
CREATE (Pollo_Campero)-[:Horario]->(Desayuno)
CREATE (Pollo_Campero)-[:Horario]->(Almuerzo)
CREATE (Pollo_Campero)-[:Horario]->(Cena)
CREATE (Pollo_Campero)-[:Horario]->(Brunch)
CREATE (Kacao)-[:Horario]->(Desayuno)
CREATE (Kacao)-[:Horario]->(Almuerzo)
CREATE (Kacao)-[:Horario]->(Cena)
CREATE (Kacao)-[:Horario]->(Brunch)
CREATE (Altuna)-[:Horario]->(Desayuno)
CREATE (Altuna)-[:Horario]->(Almuerzo)
CREATE (Altuna)-[:Horario]->(Cena)
CREATE (Altuna)-[:Horario]->(Brunch)